# Generated by Django 6.0.3 on 2026-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='sms_alerts',
        ),
        migrations.AddField(
            model_name='employer',
            name='dti_permit',
            field=models.FileField(blank=True, null=True, upload_to='dti_permits/'),
        ),
    ]
